<?php

return [
    'monthly_fixed_cost' => [
        [
            'name' => '住宅費',
            'code' => 'housing_cost',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '水道光熱費',
            'code' => 'utilities_cost',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '社会保険料',
            'code' => 'social_insurance',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '生命保険料',
            'code' => 'life_insurance',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '教育費',
            'code' => 'monthly_education_cost',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '通信費',
            'code' => 'communication_cost',
            'groupCode' => 'monthly_fixed_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
    ],
    'monthly_variable_cost' => [
        [
            'name' => '食費',
            'code' => 'food_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '日用品費',
            'code' => 'daily_goods_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '美容費',
            'code' => 'beauty_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '被服費',
            'code' => 'clothing_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '医療費',
            'code' => 'medical_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => '交通費',
            'code' => 'transportation_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
        [
            'name' => 'ガソリン費',
            'code' => 'gasoline_cost',
            'groupCode' => 'monthly_variable_cost',
            'period' => 1,
            'periodType' => 'monthly',
            'amount' => null,
        ],
    ],
    'occasional_fixed_cost' => [
        [
            'name' => '税金',
            'code' => 'tax_cost',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '火災保険料',
            'code' => 'fire_insurance',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '自動車保険',
            'code' => 'auto_insurance',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '年会費',
            'code' => 'annual_fee',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '車検費',
            'code' => 'vehicle_inspection_fee',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '教育費',
            'code' => 'occasional_education_cost',
            'groupCode' => 'occasional_fixed_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
    ],
    'occasional_variable_cost' => [
        [
            'name' => '家電、家具',
            'code' => 'appliances_furniture',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '車修理費',
            'code' => 'car_repair_cost',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '冠婚葬祭',
            'code' => 'ceremony_cost',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '卒業入学費用',
            'code' => 'school_event_cost',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '治療費',
            'code' => 'treatment_cost',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '引っ越し',
            'code' => 'moving_cost',
            'groupCode' => 'occasional_variable_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
    ],
    'luxury_consumption_cost' => [
        [
            'name' => '交際費',
            'code' => 'entertainment_cost',
            'groupCode' => 'luxury_consumption_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '旅行費',
            'code' => 'travel_cost',
            'groupCode' => 'luxury_consumption_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
        [
            'name' => '娯楽費',
            'code' => 'recreation_cost',
            'groupCode' => 'luxury_consumption_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
    ],
    'savings_investment_cost' => [
        [
            'name' => 'つみたて投資',
            'code' => 'investment_savings',
            'groupCode' => 'savings_investment_cost',
            'period' => 1,
            'periodType' => 'yearly',
            'amount' => null,
        ],
    ],
];
